---
  - name: Varnish | Fetch signing key
    apt_key: url=http://repo.varnish-cache.org/ubuntu/GPG-key.txt state=present

  - name: Varnish | Add Varnish repository
    apt_repository: repo="deb http://repo.varnish-cache.org/ubuntu/ trusty varnish-4.0" state=present

  - name: Varnish | Install Varnish package
    apt: pkg=varnish state=present update_cache=yes

  - name: Varnish | Push default configuration template
    template: src=varnish dest=/etc/default/varnish owner=root group=root mode=0644

  - name: Varnish | Push WordPress ready VCL
    template: src=default.vcl dest=/etc/varnish/default.vcl owner=root group=root mode=0644
    notify: restart varnish
