---
  - name: Install PHP5-FPM
    apt: pkg=php5-fpm state=present update_cache=yes
    tags: php5fpm

  - name: Install PHP5-FPM-MYSQL
    apt: pkg=php5-mysql state=present
    tags: php5fpm

  - name: Install PHP5-Memcache
    apt: pkg=php5-memcached state=present

  - name: Install PHP5-CLI
    apt: pkg=php5-cli state=present
    tags: php5fpm

  - name: Install PHP5-Curl
    apt: pkg=php5-curl state=present
    tags: php5fpm

  - name: Copy php.ini
    template: src=php.ini dest=/etc/php5/fpm/php.ini
    tags: php5fpm

  - name: Copy www.conf
    template: src=www.conf dest=/etc/php5/fpm/pool.d/www.conf
    notify: restart php5fpm
    tags: php5fpm
