---
  - name: Add mariadb key
    apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcbcb082a1bb943db state=present
    tags: mariadb

  - name: Add mariadb repository
    apt_repository: repo='deb http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu trusty main' state=present update_cache=yes
    tags: mariadb

  - name: Install MariaDB server package
    apt: name=mariadb-server state=present
    tags: mariadb

  - name: Start Mysql Service
    service: name=mysql state=started enabled=true
    tags: mariadb

  - name: Install python Mysql package #required for mysql_db tasks
    apt: name=python-mysqldb state=present
    tags: mariadb
