---
- name: Install Wordpress stack with Nginx, PHPFPM, MariaDB with Memcache and Varnish
  hosts: all
  user: vagrant
  # remote_user: user
  sudo: yes

  roles:
    - common
    - nginx
    - php5fpm
    - mariadb
    - memcached
    - varnish
    - wordpress
