---
- name: Install Wordpress stack with Nginx, HHVM, MariaDB with Memcache and Varnish
  hosts: all
  user: vagrant
  # remote_user: user
  sudo: yes

  roles:
    - common
    - nginx
    - hhvm
    - mariadb
    # - memcache
    - varnish
    - wordpress
