---
- name: Install Wordpress, MariaDB, Nginx, HHVM, and Varnish
  hosts: all
  user: vagrant
  # remote_user: user
  sudo: yes

  roles:
    - common
    # - mariadb
    - nginx
    # - vagrant
    # - wordpress
