---
  - name: Install Memcached
    apt: pkg=memcached state=present update_cache=yes
    tags: memcached

  - name: Copy memcached.conf
    template: src=memcached.conf dest=/etc/memcached.conf
    notify: restart memcached
    tags: memcached
