---
  - name: HHVM | Get repo key
    apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key state=present
    tags: hhvm

  - name: HHVM | Create source list
    apt_repository: repo='deb http://dl.hhvm.com/ubuntu trusty main' state=present update_cache=yes
    tags: hhvm

  - name: HHVM | Install HHVM
    apt: name=hhvm state=present
    tags: hhvm

  - name: install fast-cgi
    shell: /usr/share/hhvm/install_fastcgi.sh

  - name: HHVM | Start HHVM
    service: name=hhvm state=restarted
    tags: hhvm

  - name: restart nginx
    service: name=nginx state=restarted
