---
- name: Download Wordpress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/var/www/wordpress-{{ wp_version }}.tar.gz sha256sum="{{ wp_sha256sum }}"
  tags: wordpress

- name: Extract archive
  command: chdir=/var/www/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates=/var/www/wordpress
  tags: wordpress

- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no
  tags: wordpress

- name: Create Wordpress database
  mysql_db: name={{ wp_db_name }} state=present
  tags: wordpress

- name: Create Wordpress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present
  tags: wordpress

- name: Copy Wordpress config file
  template: src=wp-config.php dest=/var/www/wordpress/
  tags: wordpress

- name: Download WordPress CLI
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar dest=/usr/local/bin/wp
  tags: wordpress

- name: Change permissions of wp-cli
  command: chmod +x /usr/local/bin/wp
  tags: wordpress

- name: Change ownership of Wordpress installation
  file: path=/var/www/wordpress/ owner=vagrant group=vagrant state=directory recurse=yes
  tags: wordpress

# - name: WP installed?
#   command: wp core is-installed --path=/var/www/wordpress
#   sudo: no
#   register: wordpress_install
#   ignore_errors: True

- name: Install WordPress Tables
  command: wp core install
           --url="{{ wp_hostname }}"
           --title="{{ wp_site_title }}"
           --admin_user="{{ wp_admin_user }}"
           --admin_password="{{ wp_admin_password }}"
           --admin_email="{{ wp_admin_email }}"
           --path="/var/www/wordpress"
  sudo: no
  # when: wordpress_install == True
  ignore_errors: true
  tags: wordpress

- name: Set WordPress Permalinks to /%postname%/
  command: wp rewrite structure '/%postname%/' --"path=/var/www/wordpress"
  sudo: no
  ignore_errors: true
  tags: wordpress

- name: Uninstall Hello-Dolly Plugin
  command: wp plugin uninstall hello --"path=/var/www/wordpress"
  sudo: no
  ignore_errors: true
  tags: wordpress

- name: Install Varnish HTTP Purge Plugin
  command: wp plugin install varnish-http-purge --activate --"path=/var/www/wordpress"
  sudo: no
  ignore_errors: true
  tags: wordpress

- name: Install Memcached Redux Plugin
  command: wp plugin install memcached-redux --"path=/var/www/wordpress"
  sudo: no
  ignore_errors: true
  tags: wordpress

- name: Copy object-cache.php to wp-content (Memcached Redux)
  command: cp /var/www/wordpress/wp-content/plugins/memcached-redux/object-cache.php /var/www/wordpress/wp-content/object-cache.php
  tags: wordpress

- name: Install JetPack Plugin
  command: wp plugin install jetpack --"path=/var/www/wordpress"
  sudo: no
  ignore_errors: true
  tags: wordpress

- name: Install WordPress Importer Plugin
  command: wp plugin install wordpress-importer --"path=/var/www/wordpress"
  sudo: no
  ignore_errors: true
  tags: wordpress

- name: Change ownership of Wordpress installation
  file: path=/var/www/wordpress/ owner=www-data group=www-data state=directory recurse=yes
  tags: wordpress
