---
  - name: add nginx stable repository from PPA and install its signing key.
    apt_repository: repo="deb http://nginx.org/packages/ubuntu/ trusty nginx" state=present update_cache=yes

  - name: Installs nginx web server
    apt: pkg=nginx state=present force=yes
    notify: start nginx

  - name: Creates www directory
    file: path=/var/www state=directory

  - name: Copy nginx configuration
    template: src=nginx.conf dest=/etc/nginx/nginx.conf

  - name: Copy nginx configuration for wordpress
    template: src=default.conf dest=/etc/nginx/conf.d/default.conf
    notify: restart nginx
