---
  - name: Installs nginx web server
    apt: pkg=nginx state=installed update_cache=true
    notify:
      - start nginx
  # - name: Copy nginx configuration for wordpress
    # template: src=default.conf dest=/etc/nginx/conf.d/default.conf
    # notify: restart nginx
