---
  - name: Download PageSpeed Mod for NGINX
    get_url: url=https://github.com/pagespeed/ngx_pagespeed/archive/release-{{nginx_pagespeed_version}}-beta.zip dest=/tmp/nps-release-{{nginx_pagespeed_version}}-beta.zip
    tags: nginx

  - name: Unpack the compressed PageSpeed source
    command: unzip /tmp/nps-release-{{nginx_pagespeed_version}}-beta.zip chdir=/tmp creates=/tmp/ngx_pagespeed-release-{{nginx_pagespeed_version}}-beta/README
    tags: nginx

  - name: Download PageSpeed PSOL
    get_url: url=https://dl.google.com/dl/page-speed/psol/{{nginx_pagespeed_version}}.tar.gz dest=/tmp/ngx_pagespeed-release-{{nginx_pagespeed_version}}-beta/{{nginx_pagespeed_version}}.tar.gz
    tags: nginx

  - name: Extract PSOL
    command: tar -xzvf /tmp/ngx_pagespeed-release-{{nginx_pagespeed_version}}-beta/{{nginx_pagespeed_version}}.tar.gz chdir=/tmp/ngx_pagespeed-release-{{nginx_pagespeed_version}}-beta
    tags: nginx

  - name: Create the /var/ngx_pagespeed_cache folder
    file: path=/var/ngx_pagespeed_cache owner=www-data group=www-data state=directory
    tags: nginx

  - name: Download NGINX Source
    get_url: url=http://nginx.org/download/nginx-{{nginx_source_version}}.tar.gz dest=/tmp/nginx-{{nginx_source_version}}.tar.gz
    tags: nginx

  - name: Unpack the compressed Nginx source
    command: tar -xvzf /tmp/nginx-{{nginx_source_version}}.tar.gz chdir=/tmp creates=/tmp/nginx-{{nginx_source_version}}-beta/README
    tags: nginx

  - name: Compile the Nginx source
    shell: >
      cd /tmp/nginx-{{nginx_source_version}} &&
      ./configure --with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid  --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_dav_module --with-http_gzip_static_module --with-http_spdy_module --with-http_sub_module --add-module=/tmp/ngx_pagespeed-release-{{nginx_pagespeed_version}}-beta &&
      make &&
      make install
    tags: nginx

    # todo add these modules for security purposes
    #  --with-http_xslt_module
    #  --with-naxsi_module

  - name: Install the upstart init script
    template:
      src: nginx.init.d
      dest: /etc/init.d/nginx
      owner: root
      group: root
      mode: 0755
    tags: nginx

  - name: Add NGINX to startup
    command: /usr/sbin/update-rc.d -f nginx defaults
    tags: nginx

  - name: Register Nginx as a service
    service:
      name: nginx
      enabled: yes
    tags: nginx

  - name: Creates www directory
    file: path=/var/www state=directory
    tags: nginx

  - name: Copy nginx configuration
    template: src=nginx.conf dest=/etc/nginx/nginx.conf
    tags: nginx

  - name: Creates /etc/nginx/conf.d directory
    file: path=/etc/nginx/conf.d state=directory
    tags: nginx

  - name: Copy nginx configuration for wordpress
    template: src=default.conf dest=/etc/nginx/conf.d/default.conf
    notify: restart nginx
    tags: nginx
